config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'arduino_sensors#index'
  resources :arduino_sensors, :only => [:index]
  namespace :api do
    resources :arduino_sensors, :only => [:create, :show, :index]

    mount_devise_token_auth_for 'User', at: 'auth'
    get 'today' => 'arduino_sensors#today'
    get 'yesterday' => 'arduino_sensors#yesterday'
    get 'this_month' => 'arduino_sensors#this_month'
    get 'this_year' => 'arduino_sensors#this_year'
  end

  get 'today' => 'arduino_sensors#today'
  get 'yesterday' => 'arduino_sensors#yesterday'
  get 'this_month' => 'arduino_sensors#this_month'
  get 'this_year' => 'arduino_sensors#this_year'

end

app/models/arduino_sensor.rb
class ArduinoSensor < ActiveRecord::Base
  validates_presence_of :ground_humidity, :israining, :shakes, :nonrelative_asl, :relative_asl, :temperature,
                        :pressure, :air_humidity
  validates_numericality_of :ground_humidity, :shakes, :nonrelative_asl, :relative_asl, :temperature,
                            :pressure, :air_humidity
  self.per_page = 5
end

#curl -X POST  -H "Accept: Application/json" -H "Content-Type: application/json" https://weather-online-dk.herokuapp.com/api/arduino_sensors?auth_token= -d '{"ground_humidity":"99.2","israining":"1", "shakes":"10.2", "nonrelative_asl":"1000.1", "relative_asl":"999.1", "temperature":"20.1", "pressure":"999999", "air_humidity":"10.3"}' -F access-token="GG5m5EAGDxeO10mttxcE1w" -F client="e2BQMvY-Soti7FirM23dsA" -F uid="ciprojektwimiip@gmail.com"
#curl -X POST  -H "Accept: Application/json" -H "Content-Type: application/json" http://localhost:3000/api/arduino_sensors?access-token=GG5m5EAGDxeO10mttxcE1w&client=e2BQMvY-Soti7FirM23dsA&uid=ciprojektwimiip@gmail.com" -d '{"ground_humidity":"99.2","israining":"1", "shakes":"10.2", "nonrelative_asl":"1000.1", "relative_asl":"999.1", "temperature":"20.1", "pressure":"999999", "air_humidity":"10.3"}'

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules.
  devise :database_authenticatable,
           :trackable, :validatable,
           :omniauthable
  include DeviseTokenAuth::Concerns::User
end

app/controllers/api/arduino_sensors_controller.rb
class Api::ArduinoSensorsController < ApplicationController
  include DeviseTokenAuth::Concerns::SetUserByToken
  respond_to :json
  before_action :authenticate_user!, only: [:create]

  def today
    respond_with ArduinoSensor.where(:created_at => Date.today..Time.now).order(created_at: :desc)
  end

  def yesterday
    respond_with ArduinoSensor.where(:created_at => Date.yesterday..Time.now).order(created_at: :desc)
  end

  def this_month
    respond_with ArduinoSensor.where(:created_at => 1.month.ago..Time.now).order(created_at: :desc)
  end

  def this_year
    respond_with ArduinoSensor.where(:created_at => 1.year.ago..Time.now).order(created_at: :desc)
  end

  def index
    respond_with ArduinoSensor.all
  end

  def show
    respond_with ArduinoSensor.find(params[:id])
  end

  def create
    arduino_sensor = ArduinoSensor.new(arduino_sensor_params)

    if arduino_sensor.save
      render json: arduino_sensor, status: 201, location: [:api, arduino_sensor]
    else
      render json: { errors: arduino_sensor.errors }, status: 422
    end

  end

  private

  def arduino_sensor_params
    params.require(:arduino_sensor).permit(:ground_humidity, :israining, :shakes, :nonrelative_asl, :relative_asl, :temperature,
                                           :pressure, :air_humidity)
  end
end

# POST save record curl -X POST  -H "Accept: Application/json" -H "Content-Type: application/json" https://weather-online-dk.herokuapp.com/api/some_model -d '{"name":"somename","number":"1"}'
# GET single record curl -i -H "Accept: application/json" https://weather-online-dk.herokuapp.com/api/some_model/1

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include DeviseTokenAuth::Concerns::SetUserByToken
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
end

app/controllers/arduino_sensors_controller.rb
class ArduinoSensorsController < ApplicationController
  def index
    @recent = ArduinoSensor.last
    render "arduino_sensors/recent_record"
  end

  def today
    @data = ArduinoSensor.where(:created_at => Date.today..Time.now).order(created_at: :desc).paginate(:page => params[:page])
    fetch_data(@data, "There are no records from today.")
  end

  def yesterday
    @data = ArduinoSensor.where(:created_at => Date.yesterday..Time.now).order(created_at: :desc).paginate(:page => params[:page])
    fetch_data(@data,"There are no records from yesterday.")

  end

  def this_month
    @data = ArduinoSensor.where(:created_at => 1.month.ago..Time.now).order(created_at: :desc).paginate(:page => params[:page])
    fetch_data(@data, "There are no records since last month")
  end

  def this_year
    @data = ArduinoSensor.where(:created_at => 1.year.ago..Time.now).order(created_at: :desc).paginate(:page => params[:page])
    fetch_data(@data, "There are no records since last year")
  end

  private

  def fetch_data(data, alert)
    unless data.empty?
      render "arduino_sensors/index"
    else
      flash[:alert] = alert
      redirect_to root_path
    end
  end
end

#curl -i -X DELETE https://weather-online-dk.herokuapp.com/api/auth/sign_out -F access-token="<access-token>" -F client="<client>" -F uid="ciprojektwimiip@gmail.com"

#curl -X POST -v -H 'Content-Type: application/json' https://weather-online-dk.herokuapp.com/api/auth/sign_in -d '{"email": "ciprojektwimiip@gmail.com", "password": "" }'
#curl -X POST -v -H 'Content-Type: application/json' -H 'uid: ciprojektwimiip@gmail.com' -H 'access-token: <access-token>' -H 'client: <client>' https://weather-online-dk.herokuapp.com/api/arduino_sensors -d '{"ground_humidity":"99.2","israining":"1", "shakes":"10.2", "nonrelative_asl":"1000.1", "relative_asl":"999.1", "temperature":"20.1", "pressure":"999999", "air_humidity":"10.3"}'

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/some_model_controller_helper.rb
module SomeModelControllerHelper
end

app/views/arduino_sensors/_results_table.html.erb
<table id="fixed_table">
  <tr>
    <td>Temp</td>
    <td><%= data.temperature %><sup>o</sup>C</td>
  </tr>
  <tr>
    <td>Ground humidity</td>
    <td><%= data.ground_humidity %> %</td>
  </tr>
  <tr>
    <td>Shakes</td>
    <td><%= data.shakes %>%</td>
  </tr>
  <tr>
    <td>Is raining</td>
    <td><%= data.israining ? "Yes" : "No" %></td>
  </tr>
  <tr>
    <td>Non-relative Above Sea Level</td>
    <td><%= data.nonrelative_asl %>m</td>
  </tr>
  <tr>
    <td>Relative Above Sea Level</td>
    <td><%= data.relative_asl %>m</td>
  </tr>
  <tr>
    <td>Pressure</td>
    <td><%= data.pressure %>Pa</td>
  </tr>
  <tr>
    <td>Air humidity</td>
    <td><%= data.air_humidity %>%</td>
  </tr>

</table>

app/views/arduino_sensors/index.html.erb
<% @data.each do |data| %>
    <div class="panel panel-default">
        <div class="panel-heading">record from <%= data.created_at%>
            <button data-toggle="collapse" class="btn btn-primary" data-target="#demo<%=data.id %>">Details</button>
        </div>
        <div class="panel-body">
            <div id="demo<%=data.id %>" class="collapse">
                <%= render "results_table", :data => data %>
            </div>
        </div>
    </div>
<% end %>
<%= will_paginate @data, renderer: BootstrapPagination::Rails, :is_active => true %>

app/views/arduino_sensors/recent_record.html.erb
<p><b>The latest record: <%= @recent.created_at %></b></p>
<table id="fixed_table">
  <tr>
    <td>Temp</td>
    <td><%= @recent.temperature %><sup>o</sup>C</td>
  </tr>
  <tr>
    <td>Ground humidity</td>
    <td><%= @recent.ground_humidity %> %</td>
  </tr>
  <tr>
    <td>Shakes</td>
    <td><%= @recent.shakes %>%</td>
  </tr>
  <tr>
    <td>Is raining</td>
    <td><%= @recent.israining ? "Yes" : "No" %></td>
  </tr>
  <tr>
    <td>Non-relative Above Sea Level</td>
    <td><%= @recent.nonrelative_asl %>m</td>
  </tr>
  <tr>
    <td>Relative Above Sea Level</td>
    <td><%= @recent.relative_asl %>m</td>
  </tr>
  <tr>
    <td>Pressure</td>
    <td><%= @recent.pressure %>Pa</td>
  </tr>
  <tr>
    <td>Air humidity</td>
    <td><%= @recent.air_humidity %>%</td>
  </tr>

</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WeatherOnline</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default">
  <div class="container-fluid">

    <div class="navbar-header">

      <%= link_to "Arduino Weather", root_path, class: "navbar-brand" %>
    </div>
    <div>
      <ul class="nav navbar-nav">
        <li><%= link_to "Today", today_path %></li>
        <li><%= link_to "Yesterday", yesterday_path %></li>
        <li><%= link_to "Last Month", this_month_path %></li>
        <li><%= link_to "Last Year", this_year_path %></li>
      </ul>
    </div>
  </div>
</nav>

<div class="container">
  <div class="jumbotron">
    <h1>Arduino Weather</h1>
    <p>This is a web page that is presenting data from arduino sensors.</p>
    <%= link_to  "Show The Latest Record", root_path,  class: "btn btn-info"%>
  </div>
  <div class="row">
    <div class="col-sm-8" id="data_content">
      <% flash.each do |key, message| %>
          <div class="alert alert-<%= key %>">
            <%= message %>
          </div>
      <% end %>
        <%= image_tag "loadingGif.gif", id: "loading_gif", hidden:"hidden" %>
      <%= yield %>
    </div>
    <!--
    <div class="col-sm-4">
      <div class="panel-group">
        <div class="panel panel-default">
          <div class="panel-heading">Search for weather from any city around the world</div>
          <div class="panel-body">
              <form class="navbar-form">
                <div class="input-group">
                  <input type="text" class="form-control" placeholder="Search" name="q" id="city_name">
                  <div class="input-group-btn">
                    <button class="btn btn-default"  id="loadjson"><i class="glyphicon glyphicon-search"></i></button>
                  </div>
                </div>
                <h6>Powered by openweathermap API</h6>
              </form>
          </div>
        </div>
      </div>
    </div> -->
  </div>
</div>

<div class="navbar navbar-default navbar-fixed-bottom">
  <div class="container">
    <p class="navbar-text pull-left">© 2015 - Site Built By Darglk
    </p>
  </div>


</div>
</body>
</html>